### ISSUE TITLE
Windows data not readable on Linux machine

### ISSUE THREAD

**Issue by panthia** [fredserva/birdskitchen#6] opened 2020-12-15 21:17 UTC
**Describe the bug**
My data opens with my Windows version but when I try to open it with the Linux AppImage I get a black window. Initially they both opened but after I added many recipes on my Windows version the Linux version comes up all black with no menus or buttons of any kind. 

**To Reproduce**
I don't know if it is just a formatting issue because I imported recipes from another program. Not sure what to say on just how to reproduce this. 

**Expected behavior**
A database that opens without problem on Windows should open on a Linux machine since it is just a flat file. 

**Screenshots**

Screenshot would show nothing but solid black. 

**Desktop (please complete the following information):**
Ubuntu 20.04
Windows 10

**Comment by fredserva** [comment] 2020-12-17 11:27
I am unable to reproduce this bug. Can you tell me how you transfer data from Windows to Linux?

**Comment by fredserva** [comment] 2021-01-09 18:00
No one? Closing!

**Closed** 2021-01-09 18:00 UTC
Labels: bug
